#!/usr/bin/env nu

mut configs = "# this file is automatically generated, do not edit"
if $nu.os-info.family == unix {
  let wsl = $nu.os-info.family == unix and (open /proc/version --raw) =~ 'microsoft'
  configs += $"\nconst WSL = ($wsl)"
}
$configs += "\n"
let environment_script_path = $nu.config-path | path dirname | path join scripts dynamic environment.nu
echo $configs | save -f $environment_script_path
